### ISSUE TITLE
Glitch floors unplayable on Linux

### ISSUE THREAD

**Issue by d-avery** [ApacheThunder/ExpandTheGungeon#6]
I am running the latest Linux version of Enter the Gungeon on Arch Linux through Steam and whenever I open a glitch chest and go to a glitch floor, my entire screen turns pink (other than UI).
I am using the latest version of ExpandTheGungeon and ModTheGungeon at time of writing.

**Comment by ApacheThunder** [comment]
Sounds like an issue with graphics card drivers. Possible Linux doesn't support the custom shaders I used. There's not much I can do about this unfortunately. I am only able to test this mod with the Windows version of the game.

**Comment by d-avery** [comment]
Thanks for the response. If I ever test it with some other drivers, I'll post the results if it helps.

**Comment by ApacheThunder** [comment]
Oh hey I just now remembered. I added a setting awhile ago that controls whether or not to use the new shader on glitch chest floors. Go to my ExpandTheGungeon_Settings.ini file in game/resources folder (I assume it should exist for Linux as well but perhaps location might be different?)

Find the "EnableGlitchFloorScreenShader" and set it to false. This will prevent the shader from being used which should make the floors playable on Linux. It won't fix the shader but it's better then a pink screen. :P

**Comment by ApacheThunder** [comment]
While this issue has been closed for awhile now I believe this was finally corrected some time ago. As I recall the fix was to add code to detect if on Linux and if so load a different version of asset bundle. Now technically this had nothing to do with the asset bundle but with how the custom shaders used in them are compiled by Unity Editor. It looks like by adding Linux platform to my project I can build Linux targeted asset bundles and this resulted in my shaders working properly on Linux from the reports I have seen. So this issue should now be properly resolved. ;)
